/**
 * The emitted Codex helper bodies (`crossrt-2-codex-hooks`, ADR-003 / ADR-004).
 *
 * Generated-code-as-a-string, following the `generateAgentdbWriter` precedent (`setup.ts`): the
 * helpers are THIN and the logic lives in the package, because a changed helper body changes
 * codex's `currentHash` and disarms the entry until it is re-trusted (MEASURED — M0 spike §4).
 * Every byte in here is therefore a liability; keep them boring.
 *
 * ## The contracts, side by side
 *
 * |                | `dz-codex-veto.cjs` (PreToolUse)                    | `dz-codex-recall.cjs` (UserPromptSubmit) |
 * |----------------|-----------------------------------------------------|------------------------------------------|
 * | Polarity       | mode-driven on POLICY (default `warn` ⇒ exit 0)      | **never-block, always**                  |
 * | Keys on        | presence of `tool_input.command` (AM-8)              | `payload.prompt`                          |
 * | Activation     | nearest `.dz` walking up from `payload.cwd` (AM-25)  | same                                      |
 * | Our own failure| exit 0, silent, note to `helper-errors.jsonl`        | exit 0, empty stdout, no write (AM-9)     |
 *
 * `.git` is **not** an activation marker (AM-25): a user-global hook that treats "any git checkout"
 * as opted-in reaches every repository on the machine, including trees nobody pointed at dz.
 *
 * The self-failure note goes to `$CODEX_HOME/dz-hooks/helper-errors.jsonl` (AM-33), never into a
 * project — writing it into `<project>/.dz/` would CREATE a `.dz/` in a foreign repo, which is the
 * exact thing the activation rule exists to prevent.
 *
 * A `UserPromptSubmit` hook that exits 2 **blocks the user's turn**, so the recall helper has no
 * path to a non-zero exit at all.
 *
 * @packageDocumentation
 */

import { DZ_HOOK_HELPER_VERSION } from './codex-hooks.js';
import { harnessCoreDistDir } from './harness-core-location.js';

/** Shared prologue: payload read, project-root walk, never-throw error note. */
function preamble(installedDistDir: string | null): string {
  return `#!/usr/bin/env node
// GENERATED by @dzhechkov/harness-core — dz-hook-helper-version: ${DZ_HOOK_HELPER_VERSION}
// Do not edit: dz rewrites this file, and any edit disarms the hook until it is re-trusted.
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

const HELPER_VERSION = ${DZ_HOOK_HELPER_VERSION};
const CODEX_HOME = process.env.CODEX_HOME || path.join(require('node:os').homedir(), '.codex');
// The harness-core installation that EMITTED this helper, baked in at emission time.
// MEASURED 2026-09-05: with only the two project-relative candidates below, the documented
// global install ('npm i -g @dzhechkov/harness-cli') left every target repository without a
// resolvable module — every shell call reached 'guard not loaded' and was ALLOWED. It is null
// when the emitter could not name its own location; the project candidates still apply.
const INSTALLED_CORE_DIST = ${installedDistDir === null ? 'null' : JSON.stringify(installedDistDir)};
const ERROR_LOG = path.join(CODEX_HOME, 'dz-hooks', 'helper-errors.jsonl');

/**
 * Append one line to the helper NOTES log. Never throws. Never writes into a project.
 *
 * Carries BOTH self-failures and policy WARNINGS. MEASURED (M9 live probe, 2026-08-19): codex
 * surfaces a hook's stderr in the transcript ONLY when the hook exits 2 — an exit-0 hook's stderr is
 * swallowed. So a warn that lived only on stderr would be unobservable, and "the guard is live but
 * not blocking" (G-J) would be unprovable. This file is where it is observable.
 *
 * The log is 0600 inside a 0700 directory, ENFORCED on every write rather than assumed at creation:
 * \`mkdir -p\` never relaxes an existing directory's mode, so a helper dir that predates dz (or a
 * permissive umask) would leave the record world-readable (independent review, finding 8).
 */
function note(stage, err, extra) {
  try {
    try { fs.mkdirSync(path.dirname(ERROR_LOG), { recursive: true, mode: 0o700 }); } catch (_) { /* exists */ }
    try { fs.chmodSync(path.dirname(ERROR_LOG), 0o700); } catch (_) { /* not ours to tighten */ }
    try { if (!fs.existsSync(ERROR_LOG)) fs.writeFileSync(ERROR_LOG, '', { mode: 0o600 }); } catch (_) { /* raced */ }
    try { fs.chmodSync(ERROR_LOG, 0o600); } catch (_) { /* not ours to tighten */ }
    fs.appendFileSync(
      ERROR_LOG,
      JSON.stringify(Object.assign(
        { ts: new Date().toISOString(), helper: HELPER, helperVersion: HELPER_VERSION, stage, message: String((err && err.message) || err || '') },
        extra || {},
      )) + '\\n',
    );
  } catch (_) { /* the note is best-effort; it must never become the failure */ }
}

/**
 * What a note may say about a COMMAND: its hash, its program name, and a probe nonce if one is
 * embedded — never the line itself.
 *
 * A veto fires on exactly the commands most likely to carry a credential (\`ssh\`, \`curl -u\`,
 * \`psql\`), and the note is a durable file in the user's home. It recorded the full line
 * (independent review, finding 8). The hash keeps the record useful — two notes are the same
 * command iff their hashes match — and \`probeNonce\` keeps the live probe gradeable, because the
 * probe's own correlator is a purpose-built token (\`dzprobe-…\` / \`dzverify-…\`) and not a secret.
 */
function commandFacts(command) {
  var facts = {};
  try {
    facts.commandSha256 = require('node:crypto').createHash('sha256').update(String(command), 'utf8').digest('hex');
  } catch (_) { /* hashing is best-effort too */ }
  try {
    // The first token is a BINARY NAME or nothing. \`SECRET=xyz ssh …\` puts a credential in the
    // first token, and a synopsis is not worth one byte of it (fix round 2, R2-8): anything that is
    // not a plain program name — in particular anything carrying \`=\` — is redacted outright.
    var first = String(command).trim().split(/\\s+/)[0] || '';
    facts.commandSynopsis = /^[A-Za-z0-9._\\/-]+$/.test(first) ? first.slice(0, 40) : '(redacted)';
  } catch (_) { /* ignore */ }
  try {
    var m = String(command).match(/dz(?:probe|verify)-[0-9a-zA-Z-]+/);
    if (m) facts.probeNonce = m[0];
  } catch (_) { /* ignore */ }
  return facts;
}

function readPayload() {
  try {
    const raw = fs.readFileSync(0, 'utf8');
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch (err) {
    note('read-payload', err);
    return null;
  }
}

/**
 * Walk UP from cwd to the nearest directory containing a \`.dz\` DIRECTORY.
 * \`.git\` is deliberately not a marker (AM-25). No root => the helper is inert.
 */
function findProjectRoot(startDir) {
  try {
    let dir = path.resolve(startDir);
    for (let i = 0; i < 64; i += 1) {
      try {
        if (fs.statSync(path.join(dir, '.dz')).isDirectory()) return dir;
      } catch (_) { /* not here; keep walking */ }
      const parent = path.dirname(dir);
      if (parent === dir) return null;
      dir = parent;
    }
    return null;
  } catch (err) {
    note('find-root', err);
    return null;
  }
}

/**
 * FR-1 (codex-hook-root-provenance): the ONE place both hooks compute their start directory and
 * walk to a project root — replacing two independent copies of the same ternary. T1 (fix-round 1:
 * the original reproducer had an unexported \`BASE\`, so it measured the wrong file; corrected and
 * re-run — see the feature's change manifest for both) measured LIVE on \`codex-cli 0.154.0\`: three
 * real \`codex exec\` sessions (project root, a nested subdirectory, a directory with no \`.dz\`
 * anywhere in its ancestry), each with BOTH hook events (\`PreToolUse\` and \`UserPromptSubmit\`)
 * captured SEPARATELY. \`payload.cwd\` was present and equal to both \`PWD\` and the hook's own
 * \`process.cwd()\` in every one of the 6 captures. \`PWD\`/\`process.cwd()\` therefore stay only as a
 * DEFENSIVE fallback for a payload shaped without \`cwd\` — not because that fallback was ever
 * observed to fire. This is a SCOPED finding, not a claim that the "hook read the wrong project"
 * defect class cannot exist: it was not observed on codex-cli 0.154.0 across these 3 scenarios / 6
 * captures, and 01_requirements.md's own Ограничение C-3 is what permits cutting FR-3 (the explicit
 * \`DZ_PROJECT_ROOT\` override) on a scoped finding like that — not a claim of nonexistence.
 */
function resolveHookRoot(payload) {
  const hasPayloadCwd = typeof payload.cwd === 'string' && payload.cwd !== '';
  const startDir = hasPayloadCwd ? payload.cwd : (process.env.PWD || process.cwd());
  const source = hasPayloadCwd ? 'payload-cwd' : (process.env.PWD ? 'env-pwd' : 'process-cwd');
  return { root: findProjectRoot(startDir), source, startDir };
}

/**
 * Fix-round 1, item 4: a path interpolated into the provenance line below can itself carry control
 * characters — a \`payload.cwd\` from an untrusted producer, or a \`PWD\` set to something hostile —
 * and a bare newline in the middle of it would defeat the "ONE line" promise the diagnostic makes.
 * Escape the whole C0 range (0x00-0x1F) plus DEL (0x7F) into a visible \`\\n\`/\\r\`/\\t\`/\\xHH\`
 * representation; every other byte, including non-ASCII path segments, passes through unchanged.
 */
function escapeControlChars(value) {
  return String(value).replace(/[\\x00-\\x1f\\x7f]/g, function (ch) {
    var code = ch.charCodeAt(0);
    if (code === 10) return '\\\\n';
    if (code === 13) return '\\\\r';
    if (code === 9) return '\\\\t';
    return '\\\\x' + code.toString(16).padStart(2, '0');
  });
}

/**
 * FR-2: ONE provenance line, same shape as the Claude hook's (\`apply-leg.ts\`'s \`skip()\`), printed
 * to stderr. When no root was found it ALWAYS prints (the walk's whole verdict was silent before
 * this feature); when a root WAS found it prints only under \`DZ_CODEX_HOOK_DEBUG\`, so the found
 * path stays byte-for-byte silent by default (NFR-2). Tradeoff, named plainly: this line discloses
 * the absolute directory the hook was asked about (which can embed a username, a customer or
 * repository name) to stderr — accepted because it is a diagnostic aimed at the person running the
 * hook, not a return value, and redacting it would make the not-found case as silent as the bug
 * this feature exists to fix. \`startDir\`/\`root\` are escaped via \`escapeControlChars\` first, so an
 * adversarial value cannot itself defeat the "ONE line" guarantee.
 */
function reportRootProvenance(resolved) {
  if (resolved.root === null) {
    process.stderr.write(\`[\${HELPER}] skipped reason=no-project-root start=\${escapeControlChars(resolved.startDir)} (\${resolved.source})\\n\`);
    return;
  }
  if (process.env.DZ_CODEX_HOOK_DEBUG) {
    process.stderr.write(\`[\${HELPER}] root=\${escapeControlChars(resolved.root)} start=\${escapeControlChars(resolved.startDir)} (\${resolved.source})\\n\`);
  }
}

function readProjectConfig(root) {
  try {
    return JSON.parse(fs.readFileSync(path.join(root, '.dz', 'config.json'), 'utf8'));
  } catch (_) {
    return null; // absent or unreadable config is the DEFAULT case, not an error
  }
}

/**
 * Load a built module from the project's own harness-core. Never throws.
 *
 * \`import()\`, NEVER \`require()\`. \`@dzhechkov/harness-core\` is \`"type": "module"\`, so every file in
 * its \`dist/\` is an ES module, while this package supports \`node >= 20\`. \`require()\` of an ES
 * module was only unflagged in Node 20.19 / 22.12 — below that it throws ERR_REQUIRE_ESM, this
 * loader turned that into \`null\`, and a \`null\` policy is a SILENT allow. MEASURED 2026-09-05 on
 * this machine, reproducing the old loader with the flag that turns the unflagging back off:
 *   node --no-experimental-require-module <veto helper>  on  \`rm -rf .agentic-qe\`
 *   ⇒ exit 0 and an EMPTY stderr — the guard was not weak there, it was absent and mute.
 * \`import()\` loads BOTH module kinds on every supported Node, so there is one loader instead of one
 * that happens to work on the runtime that ran the tests.
 *
 * Returns \`{ mod, reason }\`. \`reason\` is the cause that was OBSERVED — the module id plus the code
 * Node reported for it — never a cause we assumed: a warning that says "no build" about an
 * ERR_REQUIRE_ESM sends the reader to fix something that is not broken.
 */
async function loadCoreDetailed(root, fileName, predicate) {
  const candidates = [
    path.join(root, 'node_modules', '@dzhechkov', 'harness-core', 'dist', fileName),
    path.join(root, 'packages', '@dzhechkov', 'harness-core', 'dist', fileName),
  ];
  // The emitting installation is the LAST resort, never the first: a project that ships its own
  // harness-core must keep using its own copy rather than being pinned to whatever emitted the hook.
  if (INSTALLED_CORE_DIST !== null) candidates.push(path.join(INSTALLED_CORE_DIST, fileName));
  const failures = [];
  for (const candidate of candidates) {
    try {
      const mod = await import(pathToFileURL(candidate).href);
      if (predicate(mod)) return { mod: mod, reason: null };
      if (mod.default && predicate(mod.default)) return { mod: mod.default, reason: null };
      failures.push(candidate + ': загружен, но нужный экспорт отсутствует');
    } catch (err) {
      const code = (err && err.code) || 'ERR_UNKNOWN';
      failures.push(candidate + ': ' + code + ' ' + String((err && err.message) || err));
      // An absent optional module is the ORDINARY case (a project may not ship every policy), so it
      // does not earn a durable note; anything else is a real load failure and does.
      if (code !== 'ERR_MODULE_NOT_FOUND') note('load-core:' + fileName, err);
    }
  }
  return { mod: null, reason: failures.join(' | ').replace(/\\s*\\n\\s*/g, ' ') };
}

/** The module only, for callers that have nothing to say about WHY it is missing. */
async function loadCore(root, fileName, predicate) {
  return (await loadCoreDetailed(root, fileName, predicate)).mod;
}
`;
}

/**
 * The PreToolUse veto helper — TWO checks behind one registry entry.
 *
 * 1. The destructive-command guard (feature `destructive-command-guard`, ADR-001): a deletion by a
 *    LITERAL path into a protected store (`.dz/`, `.agentic-qe/`, a database file). It blocks
 *    UNCONDITIONALLY, with no config mode, and that asymmetry with the shell veto below is
 *    deliberate: the shell veto's default is `warn` because its class is broad and its false-hit
 *    rate is unmeasured, while this guard's scope was cut by measurement over 20 938 real commands
 *    down to one refusal per ~510 commands (0,196 %) — narrow enough that a refusal is a fact about
 *    the command's FORM, not a judgement about its intent. The verdict, the text and the limits all
 *    come from `destructive-guard-hook.js`, the SAME module the Claude host's hook consumes, so
 *    both runtimes refuse the same commands in the same words.
 * 2. The shell veto policy: fail-OPEN on OUR failure, mode-driven on a POLICY hit. Exit 2 only when
 *    the project explicitly opted in — the shipped default warns and returns 0 (AM-24 / G-J).
 *
 * The destructive check runs FIRST and is loaded SEPARATELY, so a project whose build lacks the
 * shell-veto policy still gets it, and vice versa.
 */
export function generateCodexVetoHelper(installedDistDir: string | null = harnessCoreDistDir()): string {
  return `${preamble(installedDistDir).replace('const HELPER_VERSION', "const HELPER = 'dz-codex-veto';\nconst HELPER_VERSION")}
async function main() {
  const payload = readPayload();
  if (payload === null) return 0;

  // AM-8: key on the PRESENCE of a command, never on tool_name equality. MEASURED payload
  // (M0 spike): { tool_name: 'Bash', tool_input: { command: "…" }, cwd: "…" }.
  const input = payload.tool_input;
  const command = input && typeof input === 'object' ? input.command : undefined;
  if (typeof command !== 'string' || command === '') return 0;

  const resolved = resolveHookRoot(payload);
  reportRootProvenance(resolved);
  const root = resolved.root;
  if (root === null) return 0; // inert outside an opted-in dz project: no DECISION and no WRITE — one diagnostic line on stderr (FR-2), nothing else

  // (1) The destructive-command guard. Never blocks on our own failure: an absent module, a throw,
  // or an \`undecidable\` verdict all fall through to the shell veto below (AC-10).
  const destructiveLoad = await loadCoreDetailed(root, 'destructive-guard-hook.js', (m) => typeof m.decideDestructiveHook === 'function');
  if (destructiveLoad.mod === null) {
    // NEVER silence. A guard that could not load is indistinguishable from a guard that decided
    // "allow" unless it SAYS so, and the measurement that produced this branch is exactly that:
    // exit 0 with an empty stderr on \`rm -rf .agentic-qe\`. The exit code stays 0 — our failure is
    // not the user's violation — but it is announced on ONE line in BOTH places a human can read
    // it: the transcript, and the durable notes log (codex swallows an exit-0 stderr, M9).
    const line = 'DZ-DESTRUCTIVE-WARN: guard not loaded — ' + destructiveLoad.reason;
    process.stderr.write(line + '\\n');
    note('destructive-not-loaded', null, Object.assign(
      { marker: 'DZ-DESTRUCTIVE-WARN', reason: destructiveLoad.reason },
      commandFacts(command),
    ));
  } else {
    const destructive = destructiveLoad.mod;
    let decision = null;
    try {
      decision = destructive.decideDestructiveHook(payload, 'codex');
      // CHECKED, not assumed: a decision the helper cannot read must reach the loud path with a
      // NAME. Both \`null\` and \`{}\` are falsy at \`decision.stderr\` further down, so an unreadable
      // shape used to make the verdict simply vanish — a second door into the same silence.
      if (!decision || typeof decision.stderr !== 'string') {
        throw new TypeError('решение стража нечитаемо: ' + JSON.stringify(decision));
      }
    } catch (err) {
      // ONE line, always (round 9). The Claude hook already failed open LOUDLY here; this helper
      // only wrote a note, so in the transcript a thrown decider was indistinguishable from a clean
      // allow — the round-2 defect class (absent AND mute) reached through another door. Exit stays
      // 0, because our failure is not the user's violation, and the record lands in BOTH places a
      // human can read: the transcript, and the notes log (codex swallows an exit-0 stderr, M9).
      const why = String((err && err.message) || err).replace(/\\s*\\n\\s*/g, ' ');
      process.stderr.write('DZ-DESTRUCTIVE-WARN: classifier threw — ' + why + '\\n');
      note('destructive-threw', err, Object.assign({ marker: 'DZ-DESTRUCTIVE-WARN' }, commandFacts(command)));
      decision = null;
    }
    if (decision && decision.stderr) process.stderr.write(decision.stderr);
    if (decision && decision.exitCode === 2) {
      // The note carries the RULE and the command's hash, never the command line itself (R2-8).
      note('destructive-block', null, Object.assign({ marker: 'DZ-DESTRUCTIVE', rule: decision.rule }, commandFacts(command)));
      return 2;
    }
    if (decision && decision.stderr) {
      // MEASURED (M9): codex swallows an exit-0 hook's stderr, so a non-blocking word from this
      // guard is unobservable unless it is ALSO written where it can be read back.
      note('destructive-' + decision.outcome, null, Object.assign({ marker: 'DZ-DESTRUCTIVE-WARN' }, commandFacts(command)));
    }
  }

  // (2) The shell veto policy.
  const policy = await loadCore(root, 'shell-veto-policy.js', (m) => typeof m.vetoShellCommand === 'function');
  if (policy === null) return 0; // no logic available => allow (never block on OUR failure)

  let hit = null;
  let mode = 'warn';
  try {
    hit = policy.vetoShellCommand(command);
    mode = policy.resolveVetoMode(readProjectConfig(root));
  } catch (err) {
    note('policy', err);
    return 0;
  }
  if (hit === null || mode === 'off') return 0;

  if (mode === 'block') {
    process.stderr.write('DZ-VETO: ' + hit.rule + ' — ' + hit.reason + ' — command: ' + command + '\\n');
    note('veto-block', null, Object.assign({ marker: 'DZ-VETO', rule: hit.rule, mode: mode }, commandFacts(command)));
    return 2;
  }
  const warnLine = 'DZ-VETO-WARN: ' + hit.rule + ' — ' + hit.reason + ' — command: ' + command;
  process.stderr.write(warnLine + '\\n');
  // Codex swallows an exit-0 hook's stderr (MEASURED), so the warn is ALSO recorded where it can be
  // read back — otherwise the shipped default would be live-but-unobservable.
  note('veto-warn', null, Object.assign({ marker: 'DZ-VETO-WARN', rule: hit.rule, mode: mode }, commandFacts(command)));
  return 0;
}

// \`main\` is async because the policy loader is (\`import()\`, not \`require()\` — see loadCoreDetailed).
// The exit code still comes from exactly one place, and a rejected promise is the same fail-open as
// a thrown error was: note it, exit 0.
main()
  .catch((err) => { note('main', err); return 0; })
  .then((code) => process.exit(code === 2 ? 2 : 0));
`;
}

/**
 * The UserPromptSubmit recall helper.
 *
 * NEVER blocks and NEVER exits non-zero (AM-9). Silence is its correct output when nothing is
 * relevant, which is exactly why the acceptance canary is a FORCED HIT plus a removed-hook twin
 * (AM-4) — a dead hook and a correctly-silent one are indistinguishable from the outside.
 */
export function generateCodexRecallHelper(installedDistDir: string | null = harnessCoreDistDir()): string {
  return `${preamble(installedDistDir).replace('const HELPER_VERSION', "const HELPER = 'dz-codex-recall';\nconst HELPER_VERSION")}
const net = require('node:net');
const DAEMON_TIMEOUT_MS = 2000;

/** Ask the project's embed daemon for candidates. Resolves undefined on ANY problem. */
function askDaemon(root, prompt) {
  return new Promise((resolve) => {
    const socket = process.env.DZ_EMBED_SOCKET || path.join(root, '.dz', 'embed.sock');
    let exists = false;
    try { exists = fs.existsSync(socket); } catch (_) { exists = false; }
    if (!exists) return resolve(undefined);
    let settled = false;
    const done = (v) => {
      if (settled) return;
      settled = true;
      try { sock.destroy(); } catch (_) { /* ignore */ }
      resolve(v);
    };
    const sock = net.connect(socket);
    const timer = setTimeout(() => done(undefined), DAEMON_TIMEOUT_MS);
    if (typeof timer.unref === 'function') timer.unref();
    let buf = '';
    sock.on('connect', () => sock.write(JSON.stringify({ op: 'recall', prompt: prompt, limit: 8 }) + '\\n'));
    sock.on('data', (chunk) => {
      buf += chunk.toString('utf8');
      const nl = buf.indexOf('\\n');
      if (nl === -1) return;
      clearTimeout(timer);
      let msg = null;
      try { msg = JSON.parse(buf.slice(0, nl)); } catch (_) { msg = null; }
      done(msg && Array.isArray(msg.hits) ? msg.hits : undefined);
    });
    sock.on('error', () => { clearTimeout(timer); done(undefined); });
  });
}

async function main() {
  const payload = readPayload();
  if (payload === null) return;
  const prompt = typeof payload.prompt === 'string' ? payload.prompt : '';
  if (prompt.trim() === '') return;

  const resolved = resolveHookRoot(payload);
  reportRootProvenance(resolved);
  const root = resolved.root;
  if (root === null) return; // inert outside an opted-in dz project

  const policy = await loadCore(root, 'recall-hook-policy.js', (m) => typeof m.selectHookHits === 'function');
  if (policy === null) return;

  const candidates = await askDaemon(root, prompt);
  if (!candidates || candidates.length === 0) return; // daemon dead or nothing relevant: silence

  let selection = null;
  try {
    selection = policy.selectHookHits(prompt, candidates);
  } catch (err) {
    note('select-hits', err);
    return;
  }
  if (!selection || !Array.isArray(selection.hits) || selection.hits.length === 0) return;

  let context = '';
  try { context = policy.renderHookContext(selection); } catch (err) { note('render', err); return; }
  if (context === '') return; // empty context => print NOTHING (an empty block is noise)

  process.stdout.write(
    JSON.stringify({ hookSpecificOutput: { hookEventName: 'UserPromptSubmit', additionalContext: context } }) + '\\n',
  );

  // The usage row carries runtime: 'codex' (ADR-003 §3) through the SHARED chained appender in
  // harness-core — ONE writer implementation, two callers (AM-6/AM-7). Written AFTER stdout so a
  // logging failure can never cost the user their injection.
  const usage = await loadCore(root, 'recall-usage.js', (m) => typeof m.appendRecallUsage === 'function');
  if (usage === null) return;
  try {
    usage.appendRecallUsage({
      projectRoot: root,
      runtime: 'codex',
      query: prompt,
      runId: typeof payload.session_id === 'string' ? payload.session_id : undefined,
      hits: selection.hits.map((h) => ({ dzId: h.dzId, score: h.score })),
    });
  } catch (err) {
    note('append-usage', err);
  }
}

main()
  .catch((err) => note('main', err))
  .finally(() => process.exit(0)); // a UserPromptSubmit exit 2 BLOCKS the user's turn
`;
}

/**
 * Both helper bodies, keyed by the file they are written to.
 *
 * `installedDistDir` defaults to the harness-core doing the emitting; pass `null` for a body with
 * no absolute fallback (the pre-fix behaviour, kept so a test can prove the fallback is what makes
 * a global install work rather than asserting it).
 */
export function generateCodexHelpers(
  installedDistDir: string | null = harnessCoreDistDir(),
): Readonly<Record<'veto' | 'recall', string>> {
  return {
    veto: generateCodexVetoHelper(installedDistDir),
    recall: generateCodexRecallHelper(installedDistDir),
  };
}
