'use strict';

// The Phase-2 quality gate existed but could not block on the thing it exists to measure.
//
// MEASURED from the weight tables in scoring-system.md: a user story with NO acceptance criteria and
// NO test links loses exactly Testable (8), Completeness (10) and Traceability (10), keeps every
// other criterion legitimately full, and totals 72/100 — above the 70 READY line, filed by the
// interpretation table under "fix minor issues, then proceed". The skill whose stated job is "Block
// untestable requirements" passed it.
//
// The field report named a different pair — Measurable (8) + Traceability (10) = 82. Same arithmetic
// hole, wrong pair: Measurable scores 0 for ANY requirement without a number, and plenty of correct
// functional requirements have none, so a floor there converts a false PASS into a false BLOCK. The
// floor is closed at Testable/Completeness, and P2 below is what keeps it closed.
//
// Second half: replicate.md said "Never skip validation" and nothing checked it. Phase 3 now carries
// a precondition naming the file, both admissible verdicts, and the action on failure.
//
// These are PROMPT files a model executes, so the deterministic layer available is their content.
// Every assertion below is DISCRIMINATING: remove what it names and it goes red.

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const T = path.join(__dirname, '..', '..', 'templates', '.claude');
const read = (rel) => fs.readFileSync(path.join(T, rel), 'utf-8');

const SCORING = 'skills/requirements-validator/references/scoring-system.md';
const VALIDATOR = 'skills/requirements-validator/SKILL.md';
const REPLICATE = 'commands/replicate.md';

/** A named section of a markdown file: the heading and everything up to the next same-level one.
 *  Cross-family QE: an assertion that searches a WHOLE file passes on explanatory prose elsewhere,
 *  which is exactly the "a mention is not a rule" failure this suite exists to prevent. */
function section(src, heading, nextHeading) {
  const start = src.indexOf(heading);
  const end = src.indexOf(nextHeading, start + 1);
  assert.ok(start >= 0, 'missing section: ' + heading);
  assert.ok(end > start, 'missing section terminator: ' + nextHeading);
  return src.slice(start, end);
}

/** Phase 3 of replicate.md — placement is the property: a precondition stated in a later phase
 *  guards nothing, because the toolkit is already generated by then. */
function phase3(src) {
  const start = src.indexOf('### Phase 3: TOOLKIT GENERATION');
  const end = src.indexOf('### Phase 4');
  assert.ok(start > 0, 'replicate.md must have a Phase 3');
  assert.ok(end > start, 'replicate.md must have a Phase 4 after it');
  return src.slice(start, end);
}

describe('the Phase-2 gate must be able to block (PR-009 + PR-004)', () => {
  test('P1 — the blocking floor exists and names BOTH vetoing criteria', () => {
    const src = read(SCORING);
    assert.match(src, /Blocking floor/, 'the floor must be stated where the arithmetic lives');
    assert.match(src, /weakest link decides, never the average/,
      'the family phrase — goap-research-ed25519/SKILL.md already states this rule in these words, '
      + 'so the two skills read as one doctrine rather than two');
    assert.match(src, /`Testable`[^\n]*\|[^\n]*no acceptance criteria/,
      'Testable = 0 must veto: it is the criterion that asks whether AC exist at all');
    assert.match(src, /`Completeness`[^\n]*\|[^\n]*No AC/,
      'Completeness = 0 must veto too — the rubric\'s own "No AC" row');
    assert.match(src, /72\/100/,
      'the worked case must carry its number, or a later reader cannot check the claim');
    // Cross-family QE, the load-bearing finding: the SAME agent assigns these scores and is bound by
    // the floor, so the floor read a number the floor's subject had written. Reporting Testable = 4
    // ("vague AC") on a story with no AC evades the veto without contradicting the rubric. The floor
    // must therefore key on the artifact — a non-zero score has to quote the AC it is scoring.
    assert.match(src, /REQUIRES quoting the acceptance criteria/,
      'a non-zero Testable/Completeness must be evidenced by the AC text, not asserted');
    assert.match(src, /No quote ⇒ the score is 0/,
      'and the consequence of having no quote must be stated, or the requirement is decorative');
  });

  test('P2 — the floor is CLOSED, and says so with its reason', () => {
    // Without this, the next editor "strengthens" the gate by adding Measurable, and every
    // non-numeric functional requirement starts failing. The refusal has to be as visible as the rule.
    const src = read(SCORING);
    assert.match(src, /floor is CLOSED/, 'the list must declare itself closed');
    assert.match(src, /`Measurable`[\s\S]{0,80}deliberately NOT/,
      'Measurable must be named as excluded — naming it is what makes the exclusion survive an edit');
    assert.match(src, /false pass into a false block/,
      'the REASON must be recorded, not just the exclusion');
  });

  test('P3 — the skill\'s own verdict table carries the floor too', () => {
    // One document fixed and the other not is worse than neither: a reader who stops at SKILL.md
    // gets a verdict table that still says 72 is a minor fix.
    // Scoped to the section that CARRIES the verdict table. Searching the whole file would pass on
    // any prose that happens to mention the floor — the finding cross-family QE raised here.
    const block = section(read(VALIDATOR), '## Scoring System', '## Output Format');
    assert.match(block, /Blocking floor/, 'the floor must sit beside the score table it overrides');
    assert.match(block, /Testable = 0/, 'and name the first vetoing criterion');
    assert.match(block, /Completeness = 0/, 'and the second');
    assert.match(block, /REQUIRES quoting/, 'and carry the evidence rule, not only the veto');
  });

  test('P4 — Phase 3 states a checkable precondition: file, verdicts, action', () => {
    const block = phase3(read(REPLICATE));
    assert.match(block, /docs\/validation-report\.md/,
      'the precondition must name the FILE — "validated docs" is not checkable');
    assert.match(block, /must EXIST/, 'existence is the first check');
    // Cross-family QE: naming the three verdict emoji ANYWHERE in the phase is satisfied by prose.
    // The property is a single anchored contract — WHICH line carries the verdict, and that a
    // verdict word found elsewhere does not count.
    assert.match(block, /\*\*first line\*\* must be `\*\*Verdict:\*\*` followed by 🟢 READY or 🟡 CAVEATS/,
      'the admissible verdicts must be bound to the ONE authoritative line, not merely mentioned');
    assert.match(block, /is NOT the verdict/,
      'a verdict word elsewhere in the report must be explicitly rejected');
    assert.match(block, /more than one line starting\s+with `\*\*Verdict:\*\*`/,
      'uniqueness must be required, or two verdicts leave the reader to choose');
    assert.match(block, /do NOT generate anything/,
      'a precondition with no stated consequence is advice; the action is the rule');
    assert.match(block, /return to Phase 2/, 'and where to go instead');
  });

  test('P5 — the Phase-2 exit table carries the same floor, so both ends agree', () => {
    const src = read(REPLICATE);
    const start = src.indexOf('### Phase 2: VALIDATION');
    const end = src.indexOf('### Phase 3');
    const block = src.slice(start, end);
    assert.ok(start > 0 && end > start, 'replicate.md must have a Phase 2 before Phase 3');
    assert.match(block, /blocking floor/,
      'the phase that DECIDES the verdict must state the floor, not only the phase that consumes it');
    assert.match(block, /`Testable = 0`/, 'named in the NEEDS WORK row');
    assert.match(block, /`Completeness = 0`/, 'both of them');
  });

  test('P7 — Phase 2 EMITS the anchored verdict line Phase 3 reads', () => {
    // A reader-side contract with no writer-side obligation is half a contract: Phase 3 would demand
    // a first-line **Verdict:** that Phase 2 was never told to write, and every run would bounce.
    const src = read(REPLICATE);
    const block = src.slice(src.indexOf('### Phase 2: VALIDATION'), src.indexOf('### Phase 3'));
    assert.match(block, /\*\*first line\*\* must be exactly one of/,
      'Phase 2 must be told the exact form Phase 3 will read');
    assert.match(block, /\*\*Verdict:\*\* 🟢 READY/, 'and shown it verbatim');
    assert.match(block, /no other line in the file may begin with `\*\*Verdict:\*\*`/,
      'and told to keep it unique, which is what makes Phase 3\'s uniqueness check satisfiable');
  });

  test('P6 — the precondition is imperative and file-naming, not advisory', () => {
    const block = phase3(read(REPLICATE));
    assert.ok(!/make sure|try to|ideally|should probably/i.test(block),
      'advisory wording would pass a reviewer and instruct nothing');
    // "Never skip validation" was TRUE, imperative, and unenforceable — it named no file to read.
    // The NEVER line must now point at the check rather than stand alone.
    // Cross-family QE was right that the first version accepted a self-attestation: a line reading
    // "this is CHECKED, not assumed" is a CLAIM about the rule, and a claim is what the old advisory
    // line already was. What makes the NEVER line non-advisory is that it POINTS at a named,
    // readable artifact — so that is what this asserts.
    const src = read(REPLICATE);
    assert.match(src, /Never skip validation[^\n]*\n?[^\n]*`\*\*Verdict:\*\*` line of `docs\/validation-report\.md`/,
      'the NEVER line must point at the exact line of the exact file that enforces it');
  });
});
