/**
 * Intelligence report generator — markdown output.
 *
 * @packageDocumentation
 */

import type { IntelligenceReport, RepoProfile, ScanResult } from './types.js';

/** Generate a markdown intelligence report from scan results. */
export function generateReport(scan: ScanResult): IntelligenceReport {
  const now = new Date().toISOString();
  const integrate = scan.repos.filter((r) => r.recommendation === 'integrate');
  const monitor = scan.repos.filter((r) => r.recommendation === 'monitor');
  const skip = scan.repos.filter((r) => r.recommendation === 'skip');

  const lines: string[] = [
    '# Scout Intelligence Report',
    '',
    `**Generated:** ${now}`,
    `**Topics:** ${scan.topics.join(', ')}`,
    `**Total found:** ${scan.totalFound} | **Scanned:** ${scan.repos.length} | **New:** ${scan.newSinceLastScan}`,
    '',
    '---',
    '',
    '## Summary',
    '',
    `| Category | Count |`,
    `|----------|-------|`,
    `| Integrate | ${integrate.length} |`,
    `| Monitor | ${monitor.length} |`,
    `| Skip | ${skip.length} |`,
    '',
  ];

  if (integrate.length > 0) {
    lines.push('## 🟢 Integrate (high relevance)', '');
    lines.push(...repoTable(integrate));
  }

  if (monitor.length > 0) {
    lines.push('## 🟡 Monitor (watch for growth)', '');
    lines.push(...repoTable(monitor));
  }

  if (skip.length > 0) {
    lines.push('## ⚪ Skip (low signal)', '');
    lines.push(...repoTable(skip));
  }

  lines.push('', '---', `*Generated by @dzhechkov/scout*`);

  return {
    generatedAt: now,
    summary: {
      totalScanned: scan.repos.length,
      newDiscoveries: scan.newSinceLastScan,
      integrate: integrate.length,
      monitor: monitor.length,
      skip: skip.length,
    },
    repos: scan.repos,
    markdown: lines.join('\n'),
  };
}

function repoTable(repos: readonly RepoProfile[]): string[] {
  const lines = [
    '| Repo | Stars | Formats | Score | Novel skills |',
    '|------|-------|---------|-------|-------------|',
  ];
  for (const r of repos) {
    const formats = r.skillFormats.join(', ') || '—';
    const novel = r.novelSkills.length > 0 ? r.novelSkills.join(', ') : '—';
    lines.push(`| [${r.fullName}](${r.url}) | ${r.stars} | ${formats} | ${r.relevanceScore} | ${novel} |`);
  }
  lines.push('');
  return lines;
}
