'use strict';

const path = require('path');
const {
  green, red, yellow, cyan, bold, dim,
  info, success, error: logError,
  readManifest, fileExists, artifactState,
  COMPONENTS, getItemRelativePath,
} = require('../utils');

function run(options) {
  const { targetDir } = options;

  const manifest = readManifest(targetDir);
  if (!manifest) {
    logError('P-Replicator is not installed in this directory.');
    info(`Run ${cyan('npx @dzhechkov/p-replicator init')} first.`);
    process.exit(1);
  }

  let issues = 0;
  let warnings = 0;

  function pass(msg) { console.log(`  ${green('✓')} ${msg}`); }
  function fail(msg) { console.log(`  ${red('✗')} ${msg}`); issues++; }
  function hint(msg) { console.log(`  ${yellow('!')} ${msg}`); warnings++; }

  console.log(bold('P-Replicator — Verify state'));
  console.log(dim(`Manifest: v${manifest.version}, installed ${manifest.installedAt}`));
  console.log('');

  // ── Section 1: Pre-shipped (init contract — MUST exist) ─────────────────
  console.log(bold('Pre-shipped (from p-replicator init):'));
  console.log('');

  const preShippedGroups = Object.entries(COMPONENTS)
    .filter(([, c]) => c.kind === 'pre-shipped');

  for (const [groupKey, comp] of preShippedGroups) {
    for (const [itemKey, desc] of Object.entries(comp.items)) {
      const rel = getItemRelativePath(comp, itemKey);
      const full = path.join(targetDir, rel);
      // Display labels: commands as /name, others as group: name
      const label = groupKey === 'commands'
        ? `/${itemKey}`
        : `${groupKey}: ${itemKey}`;
      const state = artifactState(full);
      if (state === 'present') {
        pass(`${label} ${dim('— ' + desc)}`);
      } else if (state === 'empty') {
        // NOT "missing". The cures differ: missing -> run `update`; empty -> something truncated
        // your file, and `update` would silently repair it without you ever learning that. Naming
        // both "missing" moves the silence up one level instead of removing it.
        fail(`${label} — EMPTY, cannot load (${rel})`);
      } else {
        fail(`${label} — missing (${rel})`);
      }
    }
  }

  console.log('');

  // ── Section 2: Post-/replicate (project-generated — advisory) ────────────
  // Detect: was /replicate run? Heuristic: CLAUDE.md OR feature-roadmap.json present.
  const replicateRan =
    fileExists(path.join(targetDir, 'CLAUDE.md')) ||
    fileExists(path.join(targetDir, '.claude', 'feature-roadmap.json'));

  const projectGroups = Object.entries(COMPONENTS)
    .filter(([, c]) => c.kind === 'project-generated');

  if (replicateRan) {
    console.log(bold('Post-/replicate (generated by Phase 3):'));
    console.log('');
    for (const [, comp] of projectGroups) {
      for (const [itemKey, desc] of Object.entries(comp.items)) {
        const rel = getItemRelativePath(comp, itemKey);
        const full = path.join(targetDir, rel);
        if (fileExists(full)) {
          pass(`${rel} ${dim('— ' + desc)}`);
        } else {
          hint(`${rel} ${dim('— ' + desc)} (not found)`);
        }
      }
    }
  } else {
    console.log(bold('Post-/replicate:'));
    console.log(dim('  No /replicate output detected (CLAUDE.md and feature-roadmap.json both absent).'));
    console.log(dim('  Run /replicate in Claude Code to generate project-specific artifacts.'));
    console.log('');
    console.log(dim(`  Expected after /replicate (${projectGroups.reduce((n, [, c]) => n + Object.keys(c.items).length, 0)} artifacts across ${projectGroups.length} groups):`));
    for (const [groupKey, comp] of projectGroups) {
      console.log(dim(`    ${groupKey}: ${Object.keys(comp.items).length} items`));
    }
  }

  console.log('');

  // ── Summary ─────────────────────────────────────────────────────────────
  // The insights carrier: three states, none of them failing.
  //
  // FR-5 asks for three SURFACES, and the first pass shipped two — doctor and the statusline —
  // leaving verify producing identical output for absent, empty and populated. Cross-family review
  // caught it. A carrier that never existed must not read like one being used and found empty:
  // that indistinguishability is what let 27 recorded insights become 0 across four real projects.
  const insightsIndex = path.join(targetDir, '.claude', 'insights', 'index.md');
  const insightsState = artifactState(insightsIndex);
  if (insightsState === 'missing') {
    hint('insights carrier: NOT STARTED — no .claude/insights/index.md. Record one with /myinsights');
  } else if (insightsState === 'empty') {
    hint('insights carrier: EXISTS but holds ZERO entries — nothing is injected at SessionStart');
  } else {
    const entries = (require('fs').readFileSync(insightsIndex, 'utf-8')
      .match(/^##\s+\d{4}-\d{2}-\d{2}/gm) || []).length;
    pass(`insights carrier: ${entries} entr${entries === 1 ? 'y' : 'ies'} recorded`);
  }
  console.log('');

  console.log(bold('─'.repeat(60)));
  if (issues === 0 && warnings === 0) {
    success(bold('All artifacts verified.'));
  } else if (issues === 0) {
    success(`Pre-shipped contract OK (${yellow(warnings + ' post-replicate hint(s)')}).`);
  } else {
    logError(`${red(issues + ' issue(s)')} in pre-shipped contract, ${yellow(warnings + ' post-replicate hint(s)')}.`);
    console.log('');
    info(`Repair pre-shipped: ${cyan('npx @dzhechkov/p-replicator init --force')}`);
    info(`Regenerate post-pipeline: run ${cyan('/replicate')} in Claude Code`);
  }
  console.log('');

  process.exitCode = issues > 0 ? 1 : 0;
}

module.exports = run;
module.exports.run = run;
